services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketsync_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /var/www/ticketsync:/var/www/ticketsync
    env_file:
      - /var/www/ticketsync/shared/.env.production.local
    environment:
      APP_ENV: prod
